inherit_gem:
  rubocop-rails_config: config/rails.yml

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.6.6
  NewCops: enable
  Exclude:
    - 'app/assets/**/*'
    - 'bin/*'
    - 'data/**/*'
    - 'db/schema.rb'
    - 'lib/generators/folio/install_generator.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'lib/templates/lib/tasks/auto_annotate_models.rake'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'react/**/*'
    - 'test/dummy/db/schema.rb'
    - 'test/dummy/public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
