linters:
  RuboCop:
    enabled: false

exclude:
  - app/cells/folio/addresses/fields/show.slim
  - app/cells/folio/console/catalogue/published_dates/show.slim
  - app/cells/folio/console/console_notes/catalogue_tooltip/show.slim
  - app/cells/folio/console/layout/header/show.slim
  - app/cells/folio/console/layout/sidebar/title/show.slim
  - app/cells/folio/console/private_attachments/fields/show.slim
  - app/cells/folio/console/private_attachments/single_dropzone/show.slim
  - app/cells/folio/console/publishable_inputs/show.slim
  - app/cells/folio/console/users/roles_form/show.slim
  - app/cells/folio/cookie_consent/show.slim
  - app/cells/folio/devise/flash/show.slim
  - app/cells/folio/devise/modal/_close.slim
  - app/cells/folio/devise/omniauth/icon/show.slim
  - app/cells/folio/devise/password_input/show.slim
  - app/cells/folio/image/_fallback_svg.slim
  - app/cells/folio/image/_sensitive_content.slim
  - app/cells/folio/modal/_close.slim
  - app/cells/folio/ui/_typo.slim
  - app/cells/folio/ui/show.slim
  - app/components/folio/console/site_user_links/fields_component.slim
  - app/views/folio/console/accounts/_form.slim
  - app/views/folio/console/base/_private_attachments.slim
  - app/views/folio/console/menus/_form.slim
  - app/views/folio/console/pages/edit.slim
  - app/views/folio/console/pages/index.slim
  - app/views/folio/console/partials/_react_modals.slim
  - app/views/folio/console/partials/_simple_form_with_atoms.slim
  - app/views/folio/console/partials/_translations.slim
  - app/views/folio/console/ui/*.slim
  - app/views/folio/console/users/_form.slim
  - app/views/folio/console/users/show.slim
  - app/views/layouts/folio/_analytics.slim
  - app/views/layouts/folio/_cookieconsent.slim
  - app/views/layouts/folio/console/_head.slim
  - app/views/layouts/folio/console/application.slim
  - app/views/layouts/folio/mailer.html.slim
  - lib/generators/folio/console/scaffold/templates/*
  - test/dummy/app/cells/dummy/searches/show/show.slim
  - test/dummy/app/cells/dummy/ui/menu/show.slim
  - test/dummy/app/components/dummy/molecule/cards/full_width_component.slim
  - test/dummy/app/components/dummy/molecule/cards/medium_component.slim
  - test/dummy/app/components/dummy/molecule/cards/padded_image_component.slim
  - test/dummy/app/components/dummy/molecule/cards/small_component.slim
  - test/dummy/app/components/dummy/ui/footer_component.slim
  - test/dummy/app/components/dummy/ui/header_component.slim
  - test/dummy/app/components/dummy/ui/image_component.slim
  - test/dummy/app/components/dummy/ui/menu_component.slim
  - test/dummy/app/components/dummy/ui/menu_toolbar/dropdown_component.slim
  - test/dummy/app/components/dummy/ui/menu_toolbar/shopping_cart_component.slim
  - test/dummy/app/components/dummy/ui/mini_select_component.slim
  - test/dummy/app/views/dummy/home/index.slim
  - test/dummy/app/views/dummy/ui/*.slim
  - test/dummy/app/views/folio/console/dummy/playgrounds/console_notes.slim
  - test/dummy/app/views/layouts/folio/application.slim
