# frozen_string_literal: true

class Folio::Console::Dummy::Blog::ArticleAiSuggestionsController < Folio::Console::Api::BaseController
  include Folio::Console::Ai::SuggestionsControllerBase

  before_action :set_article

  private
    def set_article
      @article = Dummy::Blog::Article.find(params[:article_id])

      raise CanCan::AccessDenied unless @article.site == Folio::Current.site
    end

    def folio_ai_site
      @article.site
    end

    def folio_ai_context
      {
        title: @article.title,
        perex: @article.perex,
        meta_title: @article.meta_title,
        meta_description: @article.meta_description,
      }.compact
    end

    def folio_ai_host_eligible?
      @article.persisted? && [@article.title, @article.perex].any?(&:present?)
    end

    def folio_ai_provider_adapter
      DemoProviderAdapter.new
    end

    class DemoProviderAdapter
      def generate_suggestions(prompt:, field:, suggestion_count:)
        Array.new(suggestion_count) do |index|
          Folio::Ai::Suggestion.new(key: index + 1,
                                    text: suggestion_text(field, index),
                                    meta: { tone_label: tone_label(index) })
        end
      end

      private
        def suggestion_text(field, index)
          text = base_texts(field.key).fetch(index % 3)

          if field.character_limit.present?
            text.truncate(field.character_limit)
          else
            text
          end
        end

        def base_texts(field_key)
          case field_key.to_s
          when "title"
            [
              "Demo AI headline focused on the main editorial hook",
              "Clear demo headline with a stronger reader promise",
              "Short demo headline generated by the Folio AI panel",
            ]
          when "perex"
            [
              "Demo AI perex summarizing the article angle and giving editors a safe suggestion to accept or rewrite.",
              "Alternative demo summary that shows regeneration, copy, accept and ghost undo without a real provider.",
              "Concise AI-generated demo perex for validating the shared Folio suggestion panel.",
            ]
          when "meta_title"
            [
              "Demo SEO title for Folio AI",
              "Folio AI suggestion demo",
              "AI-generated demo meta title",
            ]
          else
            [
              "Demo meta description generated by the Folio AI panel for local verification.",
              "Alternative AI meta description showing the reusable endpoint contract.",
              "Concise demo description for checking copy, accept and undo states.",
            ]
          end
        end

        def tone_label(index)
          %w[Neutral Short Editorial].fetch(index % 3)
        end
    end
end
