# frozen_string_literal: true

# Development-only provider returning deterministic fake suggestions.
class Folio::Ai::Providers::Dummy < Folio::Ai::Providers::Base
  DEFAULT_MODEL = "dummy"

  def self.key
    :dummy
  end

  def self.available?
    Rails.env.development?
  end

  def complete(prompt:, suggestion_count:)
    texts = dummy_texts(prompt)

    {
      suggestions: suggestion_count.times.map do |index|
        { text: texts[index % texts.size] }
      end,
    }.to_json
  end

  private
    def dummy_texts(prompt)
      field_key = prompt_data(prompt).dig("field", "key").to_s

      case field_key
      when "perex"
        perex_texts
      when "meta_description"
        meta_description_texts
      when "title", "meta_title"
        title_texts(field_key)
      else
        generic_texts(field_key.presence || "field")
      end
    end

    def prompt_data(prompt)
      JSON.parse(prompt.to_s.split(Folio::Ai::TextSuggestionGenerator::CONTEXT_MARKER, 2).last.to_s)
    rescue JSON::ParserError
      {}
    end

    def perex_texts
      [
        "Dummy perex summarizing the article angle so editors can test copy, accept and undo states without a real AI request.",
        "Alternative dummy perex for validating regeneration and custom instructions in local development.",
        "Concise dummy perex generated by the development provider for the shared Folio AI panel.",
      ]
    end

    def title_texts(field_key)
      label = field_key == "meta_title" ? "meta title" : "title"

      [
        "Dummy #{label} for testing AI suggestions in local development.",
        "Alternative dummy #{label} for checking accept and undo states.",
        "Concise dummy #{label} generated by the development provider.",
      ]
    end

    def meta_description_texts
      [
        "Dummy meta description for testing search snippets in local development.",
        "Alternative dummy meta description for checking suggestion replacement.",
        "Concise dummy meta description generated by the development provider.",
      ]
    end

    def generic_texts(field_key)
      [
        "Dummy #{field_key.humanize.downcase} suggestion for local AI testing.",
        "Alternative dummy #{field_key.humanize.downcase} suggestion for regeneration checks.",
        "Concise dummy #{field_key.humanize.downcase} suggestion from the development provider.",
      ]
    end
end
